function slug(name) {
  return String(name)
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function drop(name, rarity = "common", notes, rolls) {
  return { id: slug(name), name, rarity, notes, rolls };
}

const SEARCH_ITEMS = [
  "Mirror of Kalandra",
  "Divine Orb",
  "Exalted Orb",
  "Chaos Orb",
  "Annulment Orb",
  "Vaal Orb",
  "Orb of Chance",
  "Regal Orb",
  "Orb of Alchemy",
  "Perfect Jeweller's Orb",
  "Greater Jeweller's Orb",
  "Lesser Jeweller's Orb",
  "Jeweller's Orb",
  "Gemcutter's Prism",
  "Glassblower's Bauble",
  "Artificer's Orb",
  "Armourer's Scrap",
  "Blacksmith's Whetstone",
  "Arcanist's Etcher",
  "Orb of Transmutation",
  "Orb of Augmentation",
  "Scroll of Wisdom",
  "Omen of Whittling",
  "Omen of Corruption",
  "Omen of Amelioration",
  "Omen of Dextral Exaltation",
  "Omen of Sinistral Exaltation",
  "Omen of Greater Exaltation",
  "Ancient Crisis Fragment",
  "Faded Crisis Fragment",
  "Weathered Crisis Fragment",
  "Breach Splinter",
  "Simulacrum Splinter",
  "An Audience with the King",
  "Olroth's Reliquary Key",
  "Xesht's Reliquary Key",
  "The Arbiter's Reliquary Key",
  "Ritualistic Reliquary Key",
  "Tangmazu's Reliquary Key",
  "Raven's Reflection",
  "Raven-Touched Shard",
  "Carved Mischief",
  "Carved Majesty",
  "Carved Cunning",
  "Carved Tenacity",
  "The Trialmaster's Reliquary Key",
  "Zarokh's Reliquary Key",
  "Seraph's Heart",
  "Depleted Mana Rune",
  "Duality",
  "Eventide Petals",
  "Distilled Ire",
  "Distilled Isolation",
  "Distilled Guilt",
  "Orb of Sacrifice",
  "Yaomac's Orb of Sacrifice",
  "Yugul's Orb of Sacrifice",
  "Kamasa's Orb of Sacrifice",
  "Kopec's Orb of Sacrifice",
  "Architect's Orb",
  "Ancient Infuser",
  "Core Destabiliser",
  "Crystallised Corruption",
  "Orb of Extraction",
  "Vaal Cultivation Orb",
  "Vaal Infuser",
  "Vaal Siphoner",
  "Atziri's Medallion",
  "Royal Access Chamber",
  "Azcapa's Medallion",
  "Xopec's Medallion",
  "Juatalotli's Medallion",
  "Hayoxi's Medallion",
  "Quipolatl's Medallion",
  "Uromoti's Medallion",
  "Estazunti's Medallion",
  "Puhuarte's Medallion",
  "Zantipi's Medallion",
  "Arbiter's Ignition",
  "Prototype Seventeen",
  "Her Declaration",
  "Tul's Stillness",
  "Uul-Netol's Embrace",
  "Xoph's Pyre",
  "Esh's Radiance",
  "Uhtred's Exodus",
  "Uhtred's Omen",
  "Uhtred's Augury",
  "Ixchel's Torment",
  "Tecrod's Revenge",
  "Hayoxi's Fulmination",
  "Guatelitzi's Ablation",
].map((name) => drop(name));

const ROLL_POOLS = {
  morior: [
    "+(5-7) to all Attributes per Socket filled",
    "+(8-10)% to all Elemental Resistances per Socket filled",
    "+(45-60) to maximum Life per Socket filled",
    "+(50-60) to maximum Mana per Socket filled",
    "+(10-13)% to Chaos Resistance per Socket filled",
    "(9-12)% increased Global Armour, Evasion and Energy Shield per Socket filled",
    "(8-12) Life Regeneration per second per Socket filled",
    "Hits against you have (15-20)% reduced Critical Damage Bonus per Socket filled",
    "+(10-14) to Spirit per Socket filled",
    "+(70-90) to Stun Threshold per Socket filled",
  ],
  grip: [
    "(60-100)% increased Magnitude of Abyssal Wasting you inflict",
    "Abyssal Wasting you inflict has Infinite Duration",
    "Abyssal Wasting also applies -(8-6)% to Fire Resistance",
    "Abyssal Wasting also applies -(8-6)% to Cold Resistance",
    "Abyssal Wasting also applies -(8-6)% to Lightning Resistance",
    "+(20-30)% of Armour also applies to Elemental Damage",
    "Gain (8-12)% of Damage as Extra Fire Damage",
    "Gain (8-12)% of Damage as Extra Cold Damage",
    "Gain (8-12)% of Damage as Extra Lightning Damage",
    "+(20-25) to Spirit while you have at least 200 Strength",
    "+(20-25) to Spirit while you have at least 200 Dexterity",
    "+(20-25) to Spirit while you have at least 200 Intelligence",
    "(20-30)% increased Ignite Magnitude",
    "(20-30)% increased Magnitude of Chill you inflict",
    "(15-25)% increased Magnitude of Shock you inflict",
    "(30-40)% increased Armour",
    "(30-40)% increased Evasion Rating",
    "(30-40)% increased maximum Energy Shield",
    "(15-25)% increased Area of Effect of Curses",
    "Debuffs you inflict have (12-20)% increased Slow Magnitude",
    "(6-10)% increased Spirit",
    "(4-6)% increased Strength",
    "(4-6)% increased Dexterity",
    "(4-6)% increased Intelligence",
    "+1 to Maximum Endurance Charges",
    "+1 to Maximum Frenzy Charges",
    "+1 to Maximum Power Charges",
    "Hits against you have (20-30)% reduced Critical Damage Bonus",
    "(20-10)% reduced Slowing Potency of Debuffs on You",
    "(10-16)% increased Skill Effect Duration",
    "(6-10)% increased Spirit Reservation Efficiency of Skills",
    "(30-50)% increased Thorns damage if you've consumed an Endurance Charge Recently",
    "You and Allies in your Presence have +(17-23)% to Chaos Resistance",
    "You and Allies in your Presence have (11-16)% increased Cast Speed",
    "You and Allies in your Presence have (7-12)% increased Attack Speed",
    "(25-40)% increased Critical Hit Chance",
    "(15-25)% increased Critical Damage Bonus",
    "(10-14)% of Damage is taken from Mana before Life",
    "Recover (3-5)% of your maximum Mana when an Enemy dies in your Presence",
    "Recover (2-3)% of your maximum Life when an Enemy dies in your Presence",
    "(15-25)% faster start of Energy Shield Recharge",
    "Gain Arcane Surge when a Minion Dies",
    "Gain Onslaught for 4 seconds when a Minion Dies",
    "Spell Skills have (9-18)% increased Area of Effect",
    "(9-18)% increased Area of Effect for Attacks",
    "(5-10)% increased maximum Mana",
    "(5-10)% increased maximum Life",
    "2% increased Cast Speed per 20 Spirit",
    "1% increased Attack Speed per 20 Spirit",
    "(10-20)% increased Cost Efficiency of Skills if you've consumed a Power Charge Recently",
    "(20-30)% increased amount of Life Leeched if you've consumed a Frenzy Charge Recently",
    "(30-40)% increased chance to inflict Ailments against Enemies affected by Abyssal Wasting",
    "Projectiles have (40-50)% chance for an additional Projectile when Forking",
    "Projectiles have (10-16)% chance to Chain an additional time from terrain",
    "Gain Deflection Rating equal to (10-20)% of Evasion Rating",
  ],
};

function boss(data) {
  return {
    optional: false,
    uniques: [],
    rewards: [],
    art: [],
    ...data,
  };
}

const BOSSES = [
  boss({
    id: "arbiter-of-ash",
    name: "The Arbiter of Ash",
    category: "pinnacle",
    group: "Monolith",
    act: "endgame",
    area: "The Burning Monolith",
    art: ["The Arbiter of Ash.png"],
    access: "Ancient, Faded, and Weathered Crisis Fragments from Citadels",
    uniques: [
      drop("Morior Invictus", "common", "3 random socket mods · 4 sockets", {
        pool: "morior",
        slots: 3,
        hint: "Log the 3 per-socket rolls. That's what the price hangs on.",
      }),
      drop("Ab Aeterno", "uncommon"),
      drop("Sine Aequo", "rare"),
      drop("Solus Ipse", "very-rare"),
      drop("Prism of Belief", "very-rare", "Price depends on the skill", { freeform: true, hint: "Which skill gem?" }),
      drop("Sacred Flame", "very-rare"),
      drop("The Arbiter's Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from the Arbiter of Ash pool"),
      drop("Arbiter's Ignition", "rare", "Lineage support · poe2db"),
    ],
  }),
  boss({
    id: "arbiter-of-divinity",
    name: "The Arbiter of Divinity",
    category: "pinnacle",
    group: "Apex",
    act: "endgame",
    area: "The Origin Tower",
    art: ["The Arbiter of Divinity key art.jpg"],
    access: "Origin Spark + Origin Cradle → Origin Core",
    uniques: [
      drop("Decree of Loyalty", "common"),
      drop("Decree of Acuity", "common"),
      drop("Decree of Flight", "uncommon"),
      drop("Opportunity", "uncommon"),
      drop("The Ordained", "rare"),
      drop("Immaculate Adherence", "very-rare"),
      drop("Prototype Seventeen", "rare", "Lineage support · poe2db"),
      drop("Her Declaration", "very-rare", "Lineage support"),
      drop("Seraph's Heart", "very-rare", "Lineage support"),
    ],
  }),
  boss({
    id: "king-in-the-mists-pinnacle",
    name: "The King in the Mists",
    category: "pinnacle",
    group: "Ritual",
    act: "endgame",
    area: "Crux of Nothingness",
    art: ["The King in the Mists.jpg"],
    access: "An Audience with the King at the Realmgate",
    uniques: [
      drop("Beetlebite", "common"),
      drop("Ingenuity", "common", "Belt rolls vary a lot", { freeform: true, hint: "Paste the increased bonuses" }),
      drop("The Burden of Shadows", "rare"),
      drop("From Nothing", "rare", "Price depends on the notable", { freeform: true, hint: "Which notable / keystone?" }),
      drop("Pragmatism", "very-rare"),
      drop("Ritualistic Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from the King in the Mists pool"),
      drop("Head of the King", "common", "Guaranteed"),
    ],
  }),
  boss({
    id: "the-bodach",
    name: "The Bodach",
    category: "pinnacle",
    group: "Ritual",
    act: "endgame",
    area: "Caer Tarth",
    art: ["The Bodach.png"],
    access: "Five effigy pieces, or 5× Call of the Shadows",
    uniques: [
      drop("Vestige of Darkness", "common"),
      drop("Forgotten Warden", "common"),
      drop("Sylvan's Effigy", "uncommon"),
      drop("Liminal Coil", "rare"),
      drop("Periphery", "rare"),
      drop("Catha's Brilliance", "rare", "Lineage support · poe2db"),
      drop("Mórrigan's Insight", "rare", "Lineage support"),
      drop("Paquate's Pact", "uncommon", "Lineage support · also Sealed Vault bosses"),
      drop("Carved Mischief", "rare", "Idol · socket augment"),
      drop("Carved Majesty", "very-rare", "Idol · socket augment"),
      drop("Carved Cunning", "extremely-rare", "Idol · socket augment"),
      drop("Carved Tenacity", "extremely-rare", "Idol · socket augment"),
    ],
  }),
  boss({
    id: "xesht",
    name: "Xesht, We That Are One",
    category: "pinnacle",
    group: "Breach",
    act: "endgame",
    area: "Twisted Domain",
    art: ["Xesht, We That Are One.jpg", "Xesht, We That Are One.png"],
    access: "Breachstone at the Realmgate",
    uniques: [
      drop("Beyond Reach", "common"),
      drop("Choir of the Storm", "uncommon"),
      drop("The Pandemonius", "uncommon"),
      drop("Xoph's Blood", "uncommon"),
      drop("Hand of Wisdom and Action", "rare"),
      drop("Skin of the Loyal", "rare"),
      drop("Controlled Metamorphosis", "rare", "Jewel mods vary", { freeform: true, hint: "Paste the jewel rolls" }),
      drop("Xesht's Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from the Xesht pool"),
      drop("Tul's Stillness", "rare", "Lineage support · poe2db"),
      drop("Uul-Netol's Embrace", "rare", "Lineage support · poe2db"),
      drop("Xoph's Pyre", "rare", "Lineage support · poe2db"),
      drop("Esh's Radiance", "rare", "Lineage support · poe2db"),
    ],
  }),
  boss({
    id: "olroth",
    name: "Olroth, Origin of the Fall",
    category: "pinnacle",
    group: "Expedition",
    act: "endgame",
    area: "Expedition Logbook (area level 79+)",
    art: ["Olroth, Origin of the Fall.png"],
    access: "Detonate the skull marker in a high-level Logbook",
    uniques: [
      drop("Shattered Triskelion", "common", "Always"),
      drop("Keeper of the Arc", "common"),
      drop("Olrovasara", "common"),
      drop("Svalinn", "rare"),
      drop("Heroic Tragedy", "rare"),
      drop("Olroth's Resolve", "extremely-rare"),
      drop("Olroth's Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from the Olroth pool"),
      drop("Uhtred's Exodus", "rare", "Lineage support · poe2db"),
      drop("Uhtred's Omen", "rare", "Lineage support · poe2db"),
      drop("Uhtred's Augury", "rare", "Lineage support · poe2db"),
    ],
  }),
  boss({
    id: "uhtred",
    name: "Uhtred, The Stardrinker",
    category: "pinnacle",
    group: "Expedition",
    act: "endgame",
    area: "Expedition Logbook",
    art: ["Uhtred, the Stardrinker.png"],
    access: "Random Logbook encounter",
    uniques: [
      drop("Uhtred's Crest of the Chalice", "common"),
      drop("Uhtred's Chalice", "uncommon"),
      drop("Depleted Mana Rune", "uncommon", "Right-click at 10,000 Mana → Runeseeker's Call, then reforge at the Verisium bench"),
      drop("Uhtred's Rite", "rare", "Lineage support"),
      drop("Uhtred's Constellation", "rare", "Lineage support"),
    ],
  }),
  boss({
    id: "styrn",
    name: "Styrn, Fallen Knight of Aldur",
    category: "pinnacle",
    group: "Expedition",
    act: "endgame",
    area: "Tomb of the Fallen Knight",
    art: ["Styrn, Fallen Knight of Aldur.png"],
    access: "Chance to spawn in endgame Expeditions",
    uniques: [
      drop("Olroth's Crest of the Sun", "uncommon"),
      drop("Uhtred's Crest of the Chalice", "uncommon"),
      drop("Medved's Crest of the Circle", "uncommon"),
      drop("Vorana's Crest of the Scythe", "uncommon"),
      drop("Styrn's Mountain", "rare", "Lineage support · poe2db"),
      drop("Styrn's Ferocity", "rare", "Lineage support · poe2db"),
    ],
  }),
  boss({
    id: "the-aberration",
    name: "The Aberration",
    category: "pinnacle",
    group: "Expedition",
    act: "endgame",
    area: "Ruins of Kingsmarch",
    art: ["The Aberration.png", "The Aberration.jpg"],
    access: "Reforge a Shattered Triskelion, then place it at the Verisium Center",
    uniques: [
      drop("Venerable Starlit Ore", "common", "Reforge at the Verisium Anvil → Eyes of the Runefather"),
      drop("Warding Starlit Ore", "common", "Reforge at the Verisium Anvil → Duality"),
      drop("Veridical Starlit Ore", "uncommon", "Reforge at the Verisium Anvil → Eventide Petals"),
      drop("Revered Starlit Ore", "uncommon", "Reforge at the Verisium Anvil → The Unleashed"),
      drop("Eyes of the Runefather", "rare", "From Venerable Starlit Ore at the Verisium Anvil"),
      drop("Duality", "rare", "From Warding Starlit Ore at the Verisium Anvil"),
      drop("Eventide Petals", "rare", "From Veridical Starlit Ore at the Verisium Anvil"),
      drop("The Unleashed", "rare", "From Revered Starlit Ore at the Verisium Anvil"),
      drop("Twisted Empyrean", "rare"),
      drop("Olroth's Conviction", "rare", "Lineage support"),
      drop("Olroth's Hubris", "rare", "Lineage support"),
      drop("Emergent Instinct", "rare", "Lineage support"),
      drop("Emergent Protection", "very-rare", "Lineage support"),
      drop("Emergent Vigour", "extremely-rare", "Lineage support"),
      drop("Emergent Possibility", "extremely-rare", "Lineage support"),
    ],
  }),
  boss({
    id: "simulacrum",
    name: "Simulacrum",
    category: "pinnacle",
    group: "Delirium",
    act: "endgame",
    area: "Simulacrum (Omniphobia & Kosis)",
    art: ["Simulacrum.jpg", "Kosis.png"],
    access: "Simulacrum splinters → Realmgate, clear high waves",
    uniques: [
      drop("Assailum", "common"),
      drop("Perfidy", "common"),
      drop("Melting Maelstrom", "rare"),
      drop("Collapsing Horizon", "rare"),
      drop("Strugglescream", "very-rare"),
      drop("Megalomaniac", "very-rare"),
      drop("Voices", "extremely-rare", "Unique Sapphire · 2–4 Sinister jewel sockets", { freeform: true, hint: "How many Sinister sockets? (2–4)" }),
      drop("Raven's Reflection", "rare", "Opens Tangmazu at the Withered Willow mirror"),
      drop("Tangmazu's Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from Simulacrum (Omniphobia & Kosis)"),
    ],
  }),
  boss({
    id: "tangmazu",
    name: "Tangmazu, The Raven Trickster",
    category: "pinnacle",
    group: "Delirium",
    act: "endgame",
    area: "The Withered Willow",
    art: ["Tangmazu NPC screenshot.png"],
    access: "Raven's Reflection from Simulacrum",
    uniques: [
      drop("Veilpiercer", "common"),
      drop("Sadist's Mercy", "common"),
      drop("The Auspex", "uncommon", "Tiny chance to roll Raven-Touched, which can be instilled"),
      drop("Horror's Flight", "uncommon", "Tiny chance to roll Raven-Touched, which can be instilled"),
      drop("The Raven's Flock", "rare"),
      drop("Split Personality", "rare"),
      drop("Trickster's Shard", "rare", "Lineage support"),
      drop("Tangmazu's Thurible", "rare", "Lineage support"),
      drop("Raven-Touched Shard", "very-rare", "Helmet augment · lets you anoint that helmet. Socket-bound, cannot be retrieved."),
    ],
  }),
  boss({
    id: "zarokh",
    name: "Zarokh, the Temporal",
    category: "pinnacle",
    group: "Trials",
    act: "endgame",
    area: "Trial of the Sekhemas",
    art: ["Zarokh, the Temporal.jpg", "Zarokh, the Temporal.png"],
    access: "Djinn Barya with 4 trials, area level 75+",
    uniques: [
      drop("Sandstorm Visage", "uncommon", "Changing Seasons relic"),
      drop("Safrin's Resolve", "very-rare", "Burden of Leadership relic (was Sekhema's Resolve)"),
      drop("Against the Darkness", "rare", "Desperate Alliance relic · jewel rolls vary", { freeform: true, hint: "Paste the jewel mods" }),
      drop("Temporalis", "very-rare", "Last Flame relic"),
      drop("The Burden of Leadership", "uncommon"),
      drop("The Changing Seasons", "uncommon"),
      drop("The Last Flame", "rare"),
      drop("The Desperate Alliance", "rare"),
      drop("The Peacemaker's Draught", "uncommon", "Relic · extra Baryas"),
      drop("Zarokh's Reliquary Key", "extremely-rare", "Several variants — each vault is a foiled Zarokh unique (Temporalis, Sandstorm Visage, and others)"),
      drop("Zarokh's Revolt", "rare", "Lineage support"),
      drop("Zarokh's Refrain", "rare", "Lineage support · also Zahmir"),
      drop("Varashta's Blessing", "rare", "Lineage support · also Zahmir"),
    ],
  }),
  boss({
    id: "trialmaster",
    name: "The Trialmaster",
    category: "pinnacle",
    group: "Trials",
    act: "endgame",
    area: "Temple of Chaos",
    art: ["The Trialmaster NPC screenshot.jpg"],
    access: "Inscribed Ultimatum, 10 trials, then the three Fate fragments",
    uniques: [
      drop("Glimpse of Chaos", "common"),
      drop("Zerphi's Genesis", "common"),
      drop("Mahuxotl's Machination", "uncommon"),
      drop("Hateforge", "very-rare"),
      drop("The Adorned", "very-rare", "Jewel rolls vary", { freeform: true, hint: "Paste the jewel rolls" }),
      drop("The Trialmaster's Reliquary Key", "extremely-rare", "Use at the Reliquary Vault for a foiled unique from the Trialmaster pool"),
      drop("Ixchel's Torment", "rare", "Lineage support"),
    ],
  }),
  boss({
    id: "xipocado",
    name: "Xipocado, Royal Architect",
    category: "pinnacle",
    group: "Vaal Temple",
    act: "endgame",
    area: "Architect's Chamber",
    art: ["Xipocado, Royal Architect.png"],
    access: "Path to him in Atziri's Temple. Area level 75+ is required for the Royal Access Chamber.",
    uniques: [
      drop("Royal Access Chamber", "common", "Guaranteed at temple level 75+. Place from his console."),
      drop("Azcapa's Medallion", "uncommon", "Raises medallion capacity"),
      drop("Xopec's Medallion", "uncommon", "Raises Energised Crystal capacity"),
      drop("Estazunti's Medallion", "uncommon", "Extra Restricted Room card after Architect"),
      drop("Hayoxi's Medallion", "uncommon", "Rerolls a Restricted Room"),
      drop("Juatalotli's Medallion", "uncommon", "Protects a room from destabilisation"),
      drop("Hayoxi's Fulmination", "rare", "Lineage support · Atziri's Temple"),
      drop("Guatelitzi's Ablation", "rare", "Lineage support · Atziri's Temple"),
    ],
  }),
  boss({
    id: "atziri",
    name: "Atziri, the Red Queen",
    category: "pinnacle",
    group: "Vaal Temple",
    act: "endgame",
    area: "Atziri's Chamber",
    art: ["Temple-of-atziri-1.png", "Atziri, the Red Queen.jpg"],
    access: "Architect at area level 75+, place Royal Access Chamber, path to Atziri. Kill drops a Medallion — use it at the chamber entrance to open the Vault and six Royal Troves.",
    uniques: [
      drop("Atziri's Medallion", "common", "Guaranteed. Opens the Vault at the chamber entrance."),
      drop("Drillneck", "common", "Atziri's Vault · one of the five exclusive uniques"),
      drop("Atziri's Splendour", "common", "Atziri's Vault · defence / soul-core variant matters", { freeform: true, hint: "Which defences, and which extra soul-core slots?" }),
      drop("Atziri's Rule", "uncommon", "Atziri's Vault · Reflecting Staff"),
      drop("Atziri's Contempt", "uncommon", "Atziri's Vault · Pronged Spear"),
      drop("Flesh Crucible", "rare", "Atziri's Vault · keystone jewel", { freeform: true, hint: "Which keystone, and which less-stat penalty?" }),
      drop("Atziri's Step", "uncommon", "Temple unique boots"),
      drop("Atziri's Impatience", "rare", "Lineage support · Vault extra"),
      drop("Zerphi's Infamy", "rare", "Lineage support · Vault extra"),
      drop("Atziri's Communion", "very-rare", "Lineage support · chance from the kill / Vault"),
      drop("Yaomac's Orb of Sacrifice", "uncommon", "Vault · weapons and quivers"),
      drop("Yugul's Orb of Sacrifice", "uncommon", "Vault · jewels"),
      drop("Kamasa's Orb of Sacrifice", "uncommon", "Vault · amulets, rings, belts"),
      drop("Kopec's Orb of Sacrifice", "uncommon", "Vault · armour"),
      drop("Architect's Orb", "uncommon", "Royal Trove · double-corrupt"),
      drop("Vaal Cultivation Orb", "uncommon", "Royal Trove · rerolls corrupted Vaal uniques"),
      drop("Vaal Infuser", "uncommon", "Royal Trove"),
      drop("Vaal Siphoner", "uncommon", "Royal Trove"),
      drop("Ancient Infuser", "uncommon", "Royal Trove"),
      drop("Core Destabiliser", "uncommon", "Royal Trove"),
      drop("Crystallised Corruption", "uncommon", "Royal Trove"),
      drop("Orb of Extraction", "uncommon", "Royal Trove"),
    ],
  }),
  boss({
    id: "vessel-of-kulemak",
    name: "Vessel of Kulemak",
    category: "pinnacle",
    group: "Abyss",
    act: "endgame",
    area: "Abyssal depths",
    art: ["Vessel of Kulemak.png"],
    access: "Kulemak's Invitation, then empower by defeating the three Liches",
    uniques: [
      drop("The Master's Reach", "rare"),
      drop("Grip of Kulemak", "rare", "Price depends on Desecrated mods", { slots: 4, pool: "grip", hint: "Log up to 4 Desecrated mods. This is what people price." }),
      drop("Darkness Enthroned", "rare"),
      drop("Undying Hate", "very-rare"),
      drop("The Unborn Lich", "very-rare"),
      drop("Tecrod's Revenge", "rare", "Lineage support · poe2db"),
    ],
  }),
  boss({
    id: "geonor-citadel",
    name: "Count Geonor",
    category: "citadel",
    group: "Citadel",
    act: "endgame",
    area: "Iron Citadel",
    art: ["Count Geonor.png"],
    access: "Found on the Atlas — drops a Crisis Fragment for the Arbiter",
    uniques: [drop("Ancient Crisis Fragment", "common", "Guaranteed. Used at the Burning Monolith")],
  }),
  boss({
    id: "jamanra-citadel",
    name: "Jamanra, the Abomination",
    category: "citadel",
    group: "Citadel",
    act: "endgame",
    area: "Copper Citadel",
    art: ["Jamanra, the Abomination.jpg", "JamanraAbomination.png"],
    access: "Found on the Atlas — drops a Crisis Fragment for the Arbiter",
    uniques: [drop("Faded Crisis Fragment", "common", "Guaranteed. Used at the Burning Monolith")],
  }),
  boss({
    id: "doryani-citadel",
    name: "Doryani, Royal Thaumaturge",
    category: "citadel",
    group: "Citadel",
    act: "endgame",
    area: "Stone Citadel",
    art: ["Doryani portrait.png", "Doryani trailer.png"],
    access: "Found on the Atlas — drops a Crisis Fragment for the Arbiter",
    uniques: [drop("Weathered Crisis Fragment", "common", "Guaranteed. Used at the Burning Monolith")],
  }),
];
